#' Final Herd-Level Wrap-Up Pipeline
#'
#' This function processes and consolidates livestock emissions, nutrient, and production data
#' from cohort-level inputs to herd-level outputs. It aggregates values, applies allocation shares
#' to emissions by commodity, converts emissions to CO₂-equivalent values based on the selected
#' Global Warming Potential
#'
#' @param data_cohort A `data.table` containing cohort-level data, including:
#'   - Feed (e.g., dry matter intake)
#'   - Nitrogen balance (e.g., nitrogen intake/excretion)
#'   - Production (e.g., milk, meat, fibre outputs)
#'   - Emissions (e.g., CH₄ and N₂O from various manure sources)
#'   
##' @param allocation_herd_long A `data.table` in long format, typically the output of the allocation module.
#'   It should include columns:
#'   - `ADM0_CODE`, `Animal_short`, `LPS_short`, `HerdType_short`
#'   - `commodity_name` (e.g., "Meat", "Milk")
#'   - `allocation_share` (numeric share between 0–1)
#'   - `variable_name`. Character with emission sources.
#'   
#'   
#' @param gwp Character scalar indicating which Global Warming Potential-100 conversion factors to use.
#'   Must be one of:
#'   \itemize{
#'     \item `"AR6"` — IPCC Sixth Assessment Report (default): CH₄ = 27, N₂O = 273
#'     \item `"AR5_excluding_carbon_feedback"` — IPCC AR5 (excl. feedbacks): CH₄ = 28, N₂O = 265
#'     \item `"AR5_including_carbon_feedback"` — IPCC AR5 (incl. feedbacks): CH₄ = 34, N₂O = 298
#'     \item `"AR4"` — IPCC Fourth Assessment Report: CH₄ = 25, N₂O = 298
#'   }
#'   
#' @return A named list containing:
#' \describe{
#'   \item{\code{data_cohort}}{The raw cohort-level data.}
#'   \item{\code{results_herd}}{A `data.table` in long format with allocated emissions (both as kg of gas as kgCO2eq), nutrients, and production variables at herd level.}
#' }
#'
#' @export
#' 

# RUN
# results_list<-run_wrap_up(data_cohort, allocation_herd_long)


run_wrap_up <- function(
    data_cohort,# @Yassine: this should be the big cohort-level file generated by the full pipeline!
    allocation_herd_long,#@Yassine: this should be replaced with the "ID" once introduce in the code
    gwp = "AR6"
) {
  
  # Define variable group
  
  feed_vars <- c("dmi")
  nitrogen_balance_vars <- c("dmi", "n_intake", "n_retention", "n_excretion")
 
  production_vars <- c(
    "output_milk_mass_production", "output_milk_protein_production", "output_milk_fpcm_production",
    "output_meat_production_liveweight", "output_meat_production_carcassweight",
    "output_meat_production_meat", "output_meat_production_protein", "output_fibre_production"
  )
  emissions_vars <- c(
    "ch4_enteric", "ch4_manure_pasture", "ch4_manure_burned", "ch4_manure_other",
    "direct_n2o_manure_pasture", "direct_n2o_manure_burned", "direct_n2o_manure_other",
    "indirect_n2o_manure_burned", "indirect_n2o_manure_pasture", "indirect_n2o_manure_other"
  )
  
  #1. Summing up all relevant variables in data_cohort. The file returned is at herd level (data_herd)
  data_herd <- aggregate_cohort_to_herd(
  data_cohort = data_cohort,  
  id_cols = c( "ADM0_CODE",  
               "HerdType_short",
               "Animal_short",
               "LPS_short"),
  vars_to_sum = c(feed_vars, nitrogen_balance_vars, production_vars, emissions_vars),
  cohort = "cohort"
  )
  
  
  #2. Reshaping data_herd to long format
  data_herd_long <- melt(
  data_herd,
  id.vars = c( "ADM0_CODE", # @Yassine: this should be replaced with the "ID" once introduce in the code
               "HerdType_short",
               "Animal_short",
               "LPS_short"),
  measure.vars = c(feed_vars, nitrogen_balance_vars, production_vars, emissions_vars),
  variable.name = "variable_name",
  value.name = "value"
)

  #3. Adding a grouping column in data_herd_long to facilitate filtering on other operations
  data_herd_long[
  , variable_type := fcase(
    variable_name %in% feed_vars, "Feed",
    variable_name %in% nitrogen_balance_vars, "NitrogenBalance",
    variable_name %in% production_vars, "Production",
    variable_name %in% emissions_vars, "Emissions"
  )]
  

  #4. Merge the subset of data_herd_long (with only emissions_vars) with allocation_herd_long
  
  allocation_herd_long[,allocation_type:="biophysical-energy"] # This should be a variable already included in the allocation_herd_long. Therefore, included in the allocation module.
  
  data_herd_long_allocation <- merge(
  data_herd_long[variable_type=="Emissions",],
  allocation_herd_long, #This is the output of the allocation module
  by = c("ADM0_CODE", "HerdType_short","Animal_short","LPS_short", "variable_name"), # @Yassine: this should be replaced with the "ID" once introduce in the code. "variable_name" should stay.
  all = TRUE,
  allow.cartesian = TRUE
  )
  

  
  #5. Allocate emissions to the different commodities
  data_herd_long_allocation[, value_allocated := calc_allocated_emissions(value=value, 
                                                                          allocation_share=allocation_share)]
    

  #6. Create the "gas" column
  data_herd_long_allocation[
    variable_type == "Emissions",
    gas := fcase(
      grepl("^ch4", variable_name), "CH4",
      grepl("n2o", variable_name), "N2O"
    )
  ]
  
  #7. Apply CO2eq conversion factors (GWP) to emissions resoults
  data_herd_long_allocation[
    ,  c("value_allocated_co2e", "gwp") := calc_co2eq(
    gas = gas, 
    value_allocated = value_allocated, 
    gwp = gwp) # this should be a list c=(AR6,AR5_excluding_carbon_feedback, AR5_including_carbon_feedback, AR4)).  
  ]
  
  
  
  #8. Cleaning-up emissions variables
  subset_raw<-data_herd_long_allocation[variable_type=="Emissions",.(ADM0_CODE, HerdType_short, Animal_short, LPS_short, variable_name, gas, variable_type, commodity_name, allocation_share, commodity_type, value)]
  subset_raw[,unit:="kg gas"]
  subset_raw[variable_type=="Emissions",commodity_name:="ALL"]
  subset_raw[variable_type=="Emissions",commodity_type:="ALL"]
  subset_raw[variable_type=="Emissions",allocation_share:=1]
  
  subset_allocated<-data_herd_long_allocation[variable_type=="Emissions",.(ADM0_CODE, HerdType_short, Animal_short, LPS_short, variable_name, gas, variable_type, commodity_name, allocation_share, commodity_type, value=value_allocated, allocation_type)]
  subset_allocated[,unit:="kg gas"]
  
  subset_allocatedco2e<-data_herd_long_allocation[variable_type=="Emissions",.(ADM0_CODE, HerdType_short, Animal_short, LPS_short, variable_name, gas, variable_type, commodity_name, allocation_share, commodity_type, value=value_allocated_co2e, allocation_type)]
  subset_allocatedco2e[,unit:="kg co2eq"]
  
  data_herd_long_allocation <- rbind(subset_raw, subset_allocated, use.names = TRUE,
                        fill = TRUE)
  
  data_herd_long_allocation <- rbind(data_herd_long_allocation, subset_allocatedco2e, use.names = TRUE,
                        fill = TRUE)
  
  
  
  
  #89. Combine the Emissions results allocated with other variables.
  results_herd <- rbindlist(
    list(data_herd_long_allocation, 
         data_herd_long[variable_type!="Emissions"]),
    use.names = TRUE,
    fill = TRUE
  )
  
  
  #10. Cleaning-up the table
  
  #10.1 Production
  results_herd[
    ,unit := fcase(
      variable_name %in% c("output_milk_mass_production", "output_fibre_production"), "kg",
      variable_name %in% c( "output_milk_protein_production", "output_meat_production_protein"), "kg protein",
      variable_name %in% c( "output_milk_fpcm_production"), "kg fat-protein corrected",
      variable_name %in% c("output_meat_production_liveweight"), "kg live weight",
      variable_name %in% c("output_meat_production_carcassweight"), "kg carcass weight",
      variable_name %in% c("output_meat_production_meat"), "kg bone-free meat",
      default = unit
    )]
  
  results_herd[
    , commodity_name := fcase(
      variable_name %in% c("output_milk_mass_production", "output_milk_protein_production", "output_milk_fpcm_production"), "Milk",
      variable_name %in% c("output_meat_production_liveweight", "output_meat_production_carcassweight", "output_meat_production_meat", "output_meat_production_protein"), "Meat",
      variable_name == "output_fibre_production", "Fibre",
      default = commodity_name)][
    , commodity_type := fcase(
      variable_type %in% c("Production"), "Edible",
      default = commodity_type)
    ]
    
    
  #10.2 Feed & N balance 
  results_herd[
    ,unit := fcase(
      variable_name %in% c("DryMatterIntake"), "kg dry matter",
      variable_name %in% c( "NitrogenIntake", "NitrogenRetention", "NitrogenExcretion"), "kg N",
      default = unit
    )]
  
  
  results_herd[!variable_type %in% c("Emissions", "Production")
    , commodity_name := "ALL"]
  
  results_herd[!variable_type %in% c("Emissions")
               , allocation_share := 1]
  results_herd[!variable_type %in% c("Emissions")
               , allocation_type := NA]
  
  
  #11. Renaming variables
  levels(results_herd$variable_name) <- c(
    size                          = "LivestockNumbers",
    ch4_enteric                   = "Enteric",
    ch4_manure_pasture            = "Manure-pasture",
    ch4_manure_burned             = "Manure-burned",
    ch4_manure_other              = "Manure-other",
    direct_n2o_manure_pasture     = "ManureDirect-pasture",
    direct_n2o_manure_burned      = "ManureDirect-burned",
    direct_n2o_manure_other       = "ManureDirect-other",
    indirect_n2o_manure_burned    = "ManureIndirect-burned",
    indirect_n2o_manure_pasture   = "ManureIndirect-pasture",
    indirect_n2o_manure_other     = "ManureIndirect-other",
    dmi                           = "DryMatterIntake",
    n_intake                      = "NitrogenIntake",
    n_retention                   = "NitrogenRetention",
    n_excretion                   = "NitrogenExcretion",
    output_milk_mass_production   = "MilkRaw",
    output_milk_protein_production= "MilkProtein",
    output_milk_fpcm_production   = "MilkFatProteinCorrected",
    output_meat_production_liveweight = "MeatLiveWeight",
    output_meat_production_carcassweight = "MeatCarcassWeight",
    output_meat_production_meat   = "MeatBoneFree",
    output_meat_production_protein= "MeatProtein",
    output_fibre_production       = "Fibre"
  )[levels(results_herd$variable_name)]
  
  
  #12. Variables order
  variable_order <- c(
    "ADM0_CODE",
    "HerdType_short",
    "Animal_short",
    "LPS_short",
    "variable_type",
    "variable_name",
    "unit",
    "gas",
    "allocation_type",
    "allocation_share",
    "commodity_type",
    "value"
  )
  
  setcolorder(
    results_herd,
    intersect(variable_order, names(results_herd))
  )
  
  return(list(
    data_cohort = data_cohort,
    results_herd = results_herd
  ))
}
